# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=grainger_product

# Copy the schema.sql file into the container
COPY schema.sql /docker-entrypoint-initdb.d/schema.sql

# Expose the default PostgreSQL port
EXPOSE 5432