# Build Stage
FROM openjdk:17-jdk-slim AS build

WORKDIR /app

# Copy Gradle files and download dependencies
COPY build.gradle /app/
COPY gradle /app/gradle/
COPY gradlew /app/
RUN chmod +x gradlew
RUN ./gradlew dependencies

# Copy source code and build the application JAR
COPY src /app/src/
RUN ./gradlew bootJar

# Run Stage
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/build/libs/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]